#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    --set=runtime_password="$HRIS_DATABASE_PASSWORD" <<'SQL'
CREATE ROLE hris_app LOGIN PASSWORD :'runtime_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
GRANT CONNECT ON DATABASE hris TO hris_app;
GRANT USAGE ON SCHEMA public TO hris_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hris_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hris_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hris_migrator IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO hris_app;
SQL
