plugins { id("hris.application") }

dependencies {
    implementation(projects.modules.leave.domain)
    implementation(projects.modules.leave.data)
    implementation(projects.modules.leave.delivery)
    implementation(projects.modules.workforce.domain)
    implementation(projects.modules.workforce.data)
    implementation(projects.modules.workforce.delivery)
    implementation(projects.modules.approvals.domain)
    implementation(projects.modules.approvals.data)
    implementation(projects.modules.approvals.delivery)
    implementation(projects.modules.people.domain)
    implementation(projects.modules.people.data)
    implementation(projects.modules.people.delivery)
    implementation(projects.modules.organization.domain)
    implementation(projects.modules.organization.data)
    implementation(projects.modules.organization.delivery)
    implementation(projects.modules.identity.domain)
    implementation(projects.modules.identity.data)
    implementation(projects.modules.identity.delivery)
    implementation(libs.spring.session)
    implementation(projects.core.database)
    implementation(projects.core.http)
    implementation(libs.spring.actuator)
    implementation(libs.spring.security)
    implementation(libs.jackson.kotlin)
    implementation(kotlin("reflect"))
    runtimeOnly(libs.flyway.postgresql)
    runtimeOnly(libs.postgresql)
    testImplementation(libs.spring.test)
    testImplementation(libs.spring.webmvc.test)
    testImplementation(libs.testcontainers.postgresql)
    testImplementation(libs.testcontainers.junit)
}

springBoot { mainClass.set("dev.fajar.hris.HrisApplicationKt") }
