package dev.fajar.hris.jobs.domain.entities

enum class JobKind {
    WORKFORCE_CLOSE,
    PAYROLL_CALCULATE,
    PAYROLL_FINALIZE,
    LEAVE_ACCRUAL,
    LEAVE_YEAR_CLOSE,
    DOCUMENT_VALIDATE,
    DOCUMENT_INVENTORY,
    EMPLOYEE_IMPORT_PREVIEW,
    EMPLOYEE_IMPORT_APPLY,
}
