Foreground yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 2
MaxQueue 4
ReadTimeout 30
CommandReadTimeout 5
SendBufTimeout 2000
SelfCheck 60
ConcurrentDatabaseReload no
StreamMaxLength 105M
MaxFileSize 105M
MaxScanSize 150M
MaxScanTime 60000
MaxRecursion 8
MaxFiles 1000
AlertExceedsMax yes
AlertEncrypted yes
LogTime yes
LogClean no
