CREATE ROLE hris_worker_capability NOLOGIN NOBYPASSRLS;
CREATE ROLE hris_worker_test LOGIN PASSWORD 'worker-fixture-only' INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
GRANT hris_worker_capability TO hris_worker_test;
GRANT USAGE ON SCHEMA public TO hris_worker_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO hris_worker_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO hris_worker_test;
